version: '3.3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    command: [ start-kafka.sh ]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka3855.eastus.cloudapp.azure.com
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka3855.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '9080:9080'
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
  receiver:
    build: ../receiver
    depends_on:
      - kafka
    ports:
      - "8080:8080"
  storage:
    build: ../storage
    ports:
      - "8090:8090"
    expose:
      - 8090
    depends_on:
      - db
      - kafka
  processing:
    build: ../processing
    volumes:
      - my-db:/var/lib/sqlite
    ports:
      - "8100:8100"
    depends_on:
      - storage
  audit_log:
    build: ../audit_log
    ports:
      - "8110:8110"
    depends_on:
      - kafka
  dashboard:
    build: ../dashboard-ui
    image: dashboard
    ports:
    - "3000:3000"
    depends_on:
    - "processing"
    - "audit_log"
volumes:
  my-db:
